<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <artifactId>addons-parent-pom</artifactId>
    <groupId>org.exoplatform.addons</groupId>
    <version>17</version>
  </parent>
  <groupId>org.exoplatform.addons.saml-extensions</groupId>
  <artifactId>saml-extensions-parent</artifactId>
  <version>1.0.x-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>Saml Extensions - Parent POM</name>
  <modules>
    <module>services</module>
    <module>packaging</module>
  </modules>
  <properties>
    <org.exoplatform.social.version>6.5.5-exo</org.exoplatform.social.version>
    <!-- Sonar properties -->
    <sonar.organization>exoplatform</sonar.organization>
    <org.picketlink.federation.version>2.5.5.Final</org.picketlink.federation.version>

  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.exoplatform.social</groupId>
        <artifactId>social</artifactId>
        <version>${org.exoplatform.social.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>org.picketlink</groupId>
        <artifactId>picketlink-federation</artifactId>
        <version>${org.picketlink.federation.version}</version>
        <scope>provided</scope>
      </dependency>

      <dependency>
        <!-- Missing dependency in exo-saml-addon:6.5.1 to decrypt assertions
        we add it here waiting the fix in the addon -->
        <groupId>org.apache.santuario</groupId>
        <artifactId>xmlsec</artifactId>
        <version>4.0.1</version>
      </dependency>

      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>saml-extensions-services</artifactId>
        <version>${project.version}</version>
        <scope>provided</scope>
      </dependency>
      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>saml-extensions-packaging</artifactId>
        <version>${project.version}</version>
        <scope>provided</scope>
        <type>zip</type>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <!-- This profile is used to allow github action to build branches. The github action is used for sonar analysis -->
  <profiles>
    <profile>
      <id>project-repositories</id>
      <activation>
        <property>
          <name>!skip-project-repositories</name>
        </property>
      </activation>
      <repositories>
        <repository>
          <snapshots>
            <enabled>true</enabled>
          </snapshots>
          <id>repository.exoplatform.org</id>
          <url>https://repository.exoplatform.org/public</url>
        </repository>
      </repositories>
      <pluginRepositories>
        <pluginRepository>
          <snapshots>
            <enabled>true</enabled>
          </snapshots>
          <id>repository.exoplatform.org</id>
          <url>https://repository.exoplatform.org/public</url>
        </pluginRepository>
      </pluginRepositories>
    </profile>
  </profiles>
</project>
